### PR TITLE
Fix "Show More..." twice in system prompt

### LINKED ISSUE #621: Don't show "Show More..." twice in system prompt
We have two different versions of the "Show More..." logic happening on messages now:

- System prompt has its own
- Default messages get it by default

Let's get rid of the first and only have one place where we shorten messages:

Screenshot 2024-04-29 at 8 53 57 AM

https://chatcraft.org/c/tarasglek/hiImZe7nOdAwSAJCHA4Iq

cc @mingming-ma

### PR DESCRIPTION
**Pull request by mingming-ma**
## Explanation

Update `isLongMessage` when message is system prompt.
Get rid of the system prompt "Show More..." logic and merge the "Edit to customize" logic.

## Result 

[long message chat](https://mingming-issue-621.console-overthinker-dev.pages.dev/api/share/chatcraft_dev/HHriR2E7qUbH5qdBCXx1e)

[general chat](https://mingming-issue-621.console-overthinker-dev.pages.dev/api/share/chatcraft_dev/MhLcrMYaUiPqrL3h6dJJ5)

Fixes #621

### CODE REVIEW

File: src/components/Message/MessageBase.tsx [hunk 1]
```diff
@@ -138,7 +138,9 @@ function MessageBase({
   const [imageModalOpen, setImageModalOpen] = useState<boolean>(false);
   const [selectedImage, setSelectedImage] = useState<string>("");
   const { isOpen, onToggle: originalOnToggle } = useDisclosure();
-  const isLongMessage = text.length > 5000;
+  const isSystemMessage = message instanceof ChatCraftSystemMessage;
+  const isLongMessage =
+    text.length > 5000 || (isSystemMessage && text.length > summaryText!.length);
```
Comment (humphd) [inline src/components/Message/MessageBase.tsx:143]: `summaryText!` seems bad to me, can we do something type safe?

**Review by humphd — APPROVED** [review]

**Comment by mingming-ma** [comment]
@humphd updated again as the bug below if short message
image
